In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)

In [7]:
# HP member
path_file = '../data/csv/HP_Member_EZCAP.csv'
path_export = '../output/HP_Member_20211104.txt'
df = pd.read_csv(path_file, low_memory=False, dtype={'memphone1':str})
df.to_csv(path_export, sep='|', index=False)

df.head(3)

,memnbr,memlname,memfname,memmname,memdob,memgender,subscribernbr,mcr_pbp,HICN,MRN,memaddr1,memaddr2,memaddr3,memcity,memstate,memzip,memphone1,race,race_source,ethnicity,ethnicity_source,spoken_language_s,written_language_s,other_language_s,spoken_language,written_language,other_language,guardian_lname,guardian_fname,guardian_mname,mcr_snp_type,plan_employee
0,1A05CC7XY50,PUMILIA,FRANK,J,19330708,M,1A05CC7XY50,7,1A05CC7XY50,NaN,6727 TERRENO DR,NaN,NaN,RANCHO MURIETA,CA,95683,9163542466,NaN,NaN,NaN,NaN,ENG,ENG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1A15UE0GY89,PHUONG,JOHNNY,NaN,19521115,M,1A15UE0GY89,9,1A15UE0GY89,NaN,1254 24TH AVE APT 2,NaN,NaN,SAN FRANCISCO,CA,94122,7143835399,NaN,NaN,NaN,NaN,CHI,CHI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1A16G46QH85,PHAM,NGUYET,T,19490803,F,1A16G46QH85,7,1A16G46QH85,NaN,43753 CAMERON HILLS DR,NaN,NaN,FREMONT,CA,94539,4085681562,NaN,NaN,NaN,NaN,ENG,ENG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# HP_RX
path_file = '../output/csv/HP_RX.csv'
path_export = '../output/HP_RX_20211025.txt'
df = pd.read_csv(path_file, low_memory=False, dtype={'provnbr':str, 'pharm_npi':str})
df.to_csv(path_export, sep='|', index=False)

df.head(3)

,memnbr,claim_id,provnbr,pres_fill_dt,ndc,days_suppl,claim_status,metric_qty,disp_qty,prov_npi,pharm_npi,source,src_ind
0,NaN,3119954101280G,1427282516,20210128,57237004105,7,P,28000,28,1760779375,1427282516,P,NaN
1,NaN,3551583101293G,1427282516,20210129,29300034901,90,P,90000,90,1598795395,1427282516,P,NaN
2,NaN,3671413101292B,1427282516,20210129,88221905,12,P,6000,6,1881015162,1427282516,P,NaN

In [9]:
# HP_Provider
path_file_ezcap = '../data/csv/HP_Provider.csv'
path_file_hax = '../data/csv/HEDIS HAX HP_Provider.csv'
path_export = '../output/HP_Provider_20211029.txt'

dtype = {'memzip':str,
         'memphone1':str,
         'provfax1':str,
         'provzip':str,
         'provspec1':str,
         'provspec2':str,
         'provspec3':str,
         'provspec4':str,
         'provspec5':str,
         'provspec6':str,
         'provspec7':str,
         'provspec8':str,
         'provspec9':str,
         'provspec10':str}

df_ezcap = pd.read_csv(path_file_ezcap, low_memory=False, dtype=dtype)
df_hax = pd.read_csv(path_file_hax, low_memory=False, dtype=dtype)

df = pd.concat([df_ezcap, df_hax])
df.to_csv(path_export, sep='|', index=False)

df.head(3)

,provid,provlast,provfirst,npi,licnum,tin,site_id,sitename,provaddr1,provaddr2,provaddr3,provcity,provstate,provzip,provphone1,provphone2,provfax1,provfax2,prov_type,provspec1,provspec2,provspec3,provspec4,provspec5,provspec6,provspec7,provspec8,provspec9,provspec10,provnbr
0,1003024647,DAVITA - BIXBY KNOLLS DIALYSIS,NaN,1003024647,NaN,NaN,NaN,NaN,3744 LONG BEACH BLVD,NaN,NaN,LONG BEACH,CA,908073310,5624241403,NaN,5624244310,NaN,ANCILLARY SERVICES PROVIDER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1003037508,SHMIDT,ERNEST,1003037508,NaN,NaN,NaN,NaN,1401 S GRAND AVE,NaN,NaN,LOS ANGELES,CA,900153010,2137482411,NaN,2137654097,NaN,SPECIALIST,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1003044553,AGARD,JENNIFER,1003044553,NaN,NaN,NaN,NaN,"55 FRANCISCO ST, STE 500",NaN,NaN,SAN FRANCISCO,CA,94133,4159259404,NaN,4154847045,NaN,SPECIALIST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# HP_Monthly_Mem_Data
path_file = '../data/csv/HP_MONTHLY_MEM_DATA.csv'
path_export = '../output/HP_Monthly_Mem_Data_20211104.txt'
dtype = {'dbllis_premium':str, 'dblrep_pop_id':str}
df = pd.read_csv(path_file, low_memory=False, dtype=dtype)
df.to_csv(path_export, sep='|', index=False)

df.head(3)

,dtmrun,dtmpayment,chvmemnbr,chvhospice,chvlti,dbllis_premium,dblorec,dblrep_pop_id,dblsrc_ind
0,20191207,202001,1A05CC7XY50,N,N,0,0,14129,NaN
1,20191207,202001,1A16G46QH85,N,N,0,0,14129,NaN
2,20191207,202001,1A22H95CE94,N,N,0,1,14129,NaN

In [3]:
# HP_Elig
path_file = '../data/csv/HP_Elig_EZCAP_DW.csv'
path_export = '../output/HP_Elig_20211102.txt'
dtype = {'REP_POP_ID':str}

df = pd.read_csv(path_file, low_memory=False, dtype=dtype)
df.to_csv(path_export, sep='|', index=False)

df.head(3)

,memnbr,REP_POP_ID,PO_NBR,mcd_cat,SNPTYPE,elig_start,elig_end,delig_ind,hospice_ben,medical_ben,rx_ben,dental_ben,mh_inp_ben,mh_dn_ben,mh_outer_ben,cd_inp_ben,cd_dn_ben,cd_outer_ben
0,1A05CC7XY50,14129,NaN,NaN,7,20200101,20201231,P,N,Y,Y,Y,Y,Y,Y,Y,Y,Y
1,1A14RA9QG85,14129,NaN,NaN,9,20210901,20991231,P,N,Y,Y,Y,Y,Y,Y,Y,Y,Y
2,1A15GQ4GY59,99999,NaN,NaN,11,20210101,20991231,P,N,Y,Y,Y,Y,Y,Y,Y,Y,Y

In [2]:
# Combine KS, EZCAP, HAX claims
path_file_ks = '../data/csv/HEDIS KS Claims.csv'
path_file_ezcap = '../data/csv/HEDIS EZCAP Prof hp_claims.csv'
path_file_hax = '../data/csv/HEDIS HAX HP_Claims.csv'

path_export = '../output/HP_Claim_20211108.txt'

dtype = {'provnbr':str, 'rev':str, 'units':str, 'provspec':str, 'billtype':str, 'pos':str}

df_ks = pd.read_csv(path_file_ks, low_memory=False, dtype=dtype)
df_ezcap = pd.read_csv(path_file_ezcap, low_memory=False, dtype=dtype)
df_hax = pd.read_csv(path_file_hax, low_memory=False, dtype=dtype)

df = pd.concat([df_ks, df_ezcap, df_hax])
df['fromdt'] = df['fromdt'].str.strip()
df['thrudt'] = df['thrudt'].str.strip()

df.to_csv(path_export, sep='|', index=False)

df.head(3)

,memnbr,claimid,linenbr,fromdt,thrudt,provnbr,provspec,cpt,cptmod1,cptmod2,hcpcs,cpt_ii,cpt_iimod,rev,drg,billtype,factype,pos,tos,dsc,occ_code,icd_format,diag1,diag2,diag3,diag4,diag5,diag6,diag7,diag8,diag9,diag10,diag11,diag12,diag13,diag14,diag15,diag16,diag17,diag18,diag19,diag20,surgproc1,surgproc2,surgproc3,surgproc4,surgproc5,surgproc6,claim_status,covered_days,units,source,src_ind,cpt-ii,cpt-iimod
0,1A99UU1KN20,100103847,1,01/04/2020,,1578763462,NaN,1CFK3,NaN,NaN,NaN,NaN,NaN,0023,NaN,NaN,NaN,32,NaN,NaN,NaN,10,E11621,L97522,Z4800,I739,E1140,I129,E1121,N182,E669,Z6830,Z7984,61,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN,NaN,NaN
1,1A99UU1KN20,100103847,2,01/05/2020,,1578763462,NaN,G0299,NaN,NaN,NaN,NaN,NaN,0551,NaN,NaN,NaN,32,NaN,NaN,NaN,10,E11621,L97522,Z4800,I739,E1140,I129,E1121,N182,E669,Z6830,Z7984,61,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN,NaN,NaN
2,1A99UU1KN20,100103847,3,01/06/2020,,1578763462,NaN,G0299,NaN,NaN,NaN,NaN,NaN,0551,NaN,NaN,NaN,32,NaN,NaN,NaN,10,E11621,L97522,Z4800,I739,E1140,I129,E1121,N182,E669,Z6830,Z7984,61,85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN,NaN,NaN