# Denominator Member Validation

In [1]:
import os
import pandas as pd
pd.set_option("display.max_columns", None)

In [2]:
# read last month's submission
path_submission = '../data/past_submission'

df_prev_mem = pd.read_csv(os.path.join(path_submission, 'HP_Member_20210921.txt'), sep='|', low_memory=False, dtype={'memphone1':str})
df_prev_rx = pd.read_csv(os.path.join(path_submission, 'HP_RX_20210921.txt'), sep='|', low_memory=False, dtype={'provnbr':str, 'pharm_npi':str})
df_prev_prov = pd.read_csv(os.path.join(path_submission, 'HP_Provider_20210921.txt'), sep='|', low_memory=False, dtype = {'memzip':str,
         'memphone1':str,
         'provfax1':str,
         'provzip':str,
         'provspec1':str,
         'provspec2':str,
         'provspec3':str,
         'provspec4':str,
         'provspec5':str,
         'provspec6':str,
         'provspec7':str,
         'provspec8':str,
         'provspec9':str,
         'provspec10':str})
df_prev_mthly = pd.read_csv(os.path.join(path_submission, 'HP_Monthly_Mem_Data_20210921.txt'), sep='|', low_memory=False, dtype = {'dbllis_premium':str, 'dblrep_pop_id':str})
df_prev_elig = pd.read_csv(os.path.join(path_submission, 'HP_Elig_20210921.txt'), sep='|', low_memory=False, dtype = {'REP_POP_ID':str})

# claim
df_prev_claim_ks = pd.read_csv(os.path.join(path_submission, 'HP_Claim_KS_20210921.txt'), sep='|', low_memory=False, dtype = {'provnbr':str, 'rev':str, 'units':str, 'provspec':str, 'billtype':str, 'pos':str})
df_prev_claim_ks = df_prev_claim_ks.rename(columns={'cpt-ii':'cpt_ii', 'cpt-iimod':'cpt_iimod'})
df_prev_claim_ez = pd.read_csv(os.path.join(path_submission, 'HP_Claim_EZCAP_20210921.txt'), sep='|', low_memory=False, dtype = {'provnbr':str, 'rev':str, 'units':str, 'provspec':str, 'billtype':str, 'pos':str})
df_prev_clm = pd.concat([df_prev_claim_ez, df_prev_claim_ks], ignore_index=True)

In [3]:
# read this month's submission
path_submission = '../output'

df_mem = pd.read_csv(os.path.join(path_submission, 'HP_Member_20211104.txt'), sep='|', low_memory=False, dtype={'memphone1':str})
df_rx = pd.read_csv(os.path.join(path_submission, 'HP_RX_20211025.txt'), sep='|', low_memory=False, dtype={'provnbr':str, 'pharm_npi':str})
df_prov = pd.read_csv(os.path.join(path_submission, 'HP_Provider_20211029.txt'), sep='|', low_memory=False, dtype = {'memzip':str,
         'memphone1':str,
         'provfax1':str,
         'provzip':str,
         'provspec1':str,
         'provspec2':str,
         'provspec3':str,
         'provspec4':str,
         'provspec5':str,
         'provspec6':str,
         'provspec7':str,
         'provspec8':str,
         'provspec9':str,
         'provspec10':str})
df_mthly = pd.read_csv(os.path.join(path_submission, 'HP_Monthly_Mem_Data_20211104.txt'), sep='|', low_memory=False, dtype = {'dbllis_premium':str, 'dblrep_pop_id':str})
df_elig = pd.read_csv(os.path.join(path_submission, 'HP_Elig_20211102.txt'), sep='|', low_memory=False, dtype = {'REP_POP_ID':str})
df_claim = pd.read_csv(os.path.join(path_submission, 'HP_Claim_20211108.txt'), sep='|', low_memory=False, dtype = {'provnbr':str, 'rev':str, 'units':str, 'provspec':str, 'billtype':str, 'pos':str})

# Look up member in discrepancy list
* 7E59G71FF10
* 7R54MF4VT98
* 9UR4TA0RW09
* 1Q09W15CE12

In [14]:
# parameter setup
list_memnbr_cdc = [
    '7E59G71FF10',
    '7R54MF4VT98',
    '9UR4TA0RW09',
    '1Q09W15CE12']

list_memnbr_cdc = [
    '2FG6V02JR56',
    '2Q52XQ1TC25',
    '7NW1Q71YE38']

memnbr = '7E59G71FF10'

In [15]:
# member
df_prev = df_prev_mem.query(f'memnbr == "{memnbr}"').reset_index(drop=True)
display(df_prev)

df_current = df_mem.query(f'memnbr == "{memnbr}"').reset_index(drop=True)
display(df_current)

,memnbr,memlname,memfname,memmname,memdob,memgender,subscribernbr,mcr_pbp,HICN,MRN,memaddr1,memaddr2,memaddr3,memcity,memstate,memzip,memphone1,race,race_source,ethnicity,ethnicity_source,spoken_language_s,written_language_s,other_language_s,spoken_language,written_language,other_language,guardian_lname,guardian_fname,guardian_mname,mcr_snp_type,plan_employee
0,7E59G71FF10,YANEZ,VICTORIA,NaN,19611130,F,7E59G71FF10,9,7E59G71FF10,NaN,199 BUTTERWORTH AVE,NaN,NaN,SACRAMENTO,CA,95838.0,9166765610,NaN,NaN,NaN,NaN,ENG,ENG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,memnbr,memlname,memfname,memmname,memdob,memgender,subscribernbr,mcr_pbp,HICN,MRN,memaddr1,memaddr2,memaddr3,memcity,memstate,memzip,memphone1,race,race_source,ethnicity,ethnicity_source,spoken_language_s,written_language_s,other_language_s,spoken_language,written_language,other_language,guardian_lname,guardian_fname,guardian_mname,mcr_snp_type,plan_employee
0,7E59G71FF10,YANEZ,VICTORIA,NaN,19611130,F,7E59G71FF10,9,7E59G71FF10,NaN,199 BUTTERWORTH AVE,NaN,NaN,SACRAMENTO,CA,95838,9166765610,NaN,NaN,NaN,NaN,ENG,ENG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Rx
df_prev = df_prev_rx.query(f'memnbr == "{memnbr}"').reset_index(drop=True)

n_prev = df_prev.shape[0]
print(f'{n_prev} records for previous submission.')
display(df_prev)

df_current = df_rx.query(f'memnbr == "{memnbr}"').reset_index(drop=True)

n = df_current.shape[0]
print(f'\n{n} records for current submission.')
display(df_current)

78 records for previous submission.

,memnbr,claim_id,provnbr,pres_fill_dt,ndc,days_suppl,claim_status,metric_qty,disp_qty,prov_npi,pharm_npi,source,src_ind
0,7E59G71FF10,1402828003091G,1598903130,20200309,50228011505,90,P,90000,90,1548294267,1598903130,P,NaN
1,7E59G71FF10,1403306003099B,1598903130,20200309,66993001968,17,P,18000,18,1548294267,1598903130,P,NaN
2,7E59G71FF10,1742121001159G,1598903130,20200115,33342010215,30,P,30000,30,1548294267,1598903130,P,NaN
3,7E59G71FF10,1742543001157G,1598903130,20200115,45802006405,30,P,454000,454,1548294267,1598903130,P,NaN
4,7E59G71FF10,1772567010295G,1598903130,20201029,16729004517,90,P,90000,90,1912497256,1598903130,P,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,7E59G71FF10,9411037009280G,1598903130,20200928,53746010901,30,P,120000,120,1548294267,1598903130,P,NaN
74,7E59G71FF10,9650134103240B,1124430111,20210324,173068220,30,P,18000,18,1073671038,1124430111,P,NaN
75,7E59G71FF10,9650200103240G,1124430111,20210324,16729011917,90,P,90000,90,1073671038,1124430111,P,NaN
76,7E59G71FF10,9650257103244B,1124430111,20210324,56151146004,50,P,100000,100,1801453014,1124430111,P,NaN
77,7E59G71FF10,9670879012199G,1598903130,20201219,53746010901,30,P,120000,120,1548294267,1598903130,P,NaN

78 records for current submission.

,memnbr,claim_id,provnbr,pres_fill_dt,ndc,days_suppl,claim_status,metric_qty,disp_qty,prov_npi,pharm_npi,source,src_ind
0,7E59G71FF10,1402828003091G,1598903130,20200309,50228011505,90,P,90000,90,1548294267,1598903130,P,NaN
1,7E59G71FF10,1403306003099B,1598903130,20200309,66993001968,17,P,18000,18,1548294267,1598903130,P,NaN
2,7E59G71FF10,1742121001159G,1598903130,20200115,33342010215,30,P,30000,30,1548294267,1598903130,P,NaN
3,7E59G71FF10,1742543001157G,1598903130,20200115,45802006405,30,P,454000,454,1548294267,1598903130,P,NaN
4,7E59G71FF10,1772567010295G,1598903130,20201029,16729004517,90,P,90000,90,1912497256,1598903130,P,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,7E59G71FF10,9411037009280G,1598903130,20200928,53746010901,30,P,120000,120,1548294267,1598903130,P,NaN
74,7E59G71FF10,9650134103240B,1124430111,20210324,173068220,30,P,18000,18,1073671038,1124430111,P,NaN
75,7E59G71FF10,9650200103240G,1124430111,20210324,16729011917,90,P,90000,90,1073671038,1124430111,P,NaN
76,7E59G71FF10,9650257103244B,1124430111,20210324,56151146004,50,P,100000,100,1801453014,1124430111,P,NaN
77,7E59G71FF10,9670879012199G,1598903130,20201219,53746010901,30,P,120000,120,1548294267,1598903130,P,NaN

In [17]:
# Rx mismatch prev -> current
df_prev.merge(df_current, on='claim_id', how='left', indicator=True).query('_merge != "both"')

Empty DataFrame
Columns: [memnbr_x, claim_id, provnbr_x, pres_fill_dt_x, ndc_x, days_suppl_x, claim_status_x, metric_qty_x, disp_qty_x, prov_npi_x, pharm_npi_x, source_x, src_ind_x, memnbr_y, provnbr_y, pres_fill_dt_y, ndc_y, days_suppl_y, claim_status_y, metric_qty_y, disp_qty_y, prov_npi_y, pharm_npi_y, source_y, src_ind_y, _merge]
Index: []

In [18]:
# Rx mismatch current -> current
df_current.merge(df_prev, on='claim_id', how='left', indicator=True).query('_merge != "both"')

Empty DataFrame
Columns: [memnbr_x, claim_id, provnbr_x, pres_fill_dt_x, ndc_x, days_suppl_x, claim_status_x, metric_qty_x, disp_qty_x, prov_npi_x, pharm_npi_x, source_x, src_ind_x, memnbr_y, provnbr_y, pres_fill_dt_y, ndc_y, days_suppl_y, claim_status_y, metric_qty_y, disp_qty_y, prov_npi_y, pharm_npi_y, source_y, src_ind_y, _merge]
Index: []

In [19]:
# Monthly member
df_prev = df_prev_mthly.query(f'chvmemnbr == "{memnbr}"').reset_index(drop=True)

n_prev = df_prev.shape[0]
print(f'{n_prev} records for previous submission.')
display(df_prev)

df_current = df_mthly.query(f'chvmemnbr == "{memnbr}"').reset_index(drop=True)

n = df_current.shape[0]
print(f'\n{n} records for current submission.')
display(df_current)

17 records for previous submission.

,dtmrun,dtmpayment,chvmemnbr,chvhospice,chvlti,dbllis_premium,dblorec,dblrep_pop_id,dblsrc_ind
0,20200104,202002,7E59G71FF10,N,N,32,1,14129,NaN
1,20200208,202003,7E59G71FF10,N,N,32,1,14129,NaN
2,20200307,202004,7E59G71FF10,N,N,32,1,14129,NaN
3,20200411,202005,7E59G71FF10,N,N,32,1,14129,NaN
4,20200509,202006,7E59G71FF10,N,N,32,1,14129,NaN
5,20200607,202007,7E59G71FF10,N,N,32,1,14129,NaN
6,20200711,202008,7E59G71FF10,N,N,32,1,14129,NaN
7,20200808,202009,7E59G71FF10,N,N,32,1,14129,NaN
8,20200912,202010,7E59G71FF10,N,N,32,1,14129,NaN
9,20201010,202011,7E59G71FF10,N,N,32,1,14129,NaN
10,20201107,202012,7E59G71FF10,N,N,32,1,14129,NaN
11,20201205,202101,7E59G71FF10,N,N,31.5,1,14129,NaN
12,20210110,202102,7E59G71FF10,N,N,31.5,1,14129,NaN
13,20210206,202103,7E59G71FF10,N,N,31.5,1,14129,NaN
14,20210306,202104,7E59G71FF10,N,N,31.5,1,14129,NaN
15,20210410,202105,7E59G71FF10,N,N,-31.5,1,14129,NaN
16,20210606,202107,7E59G71FF10,N,N,0,1,14129,NaN

17 records for current submission.

,dtmrun,dtmpayment,chvmemnbr,chvhospice,chvlti,dbllis_premium,dblorec,dblrep_pop_id,dblsrc_ind
0,20200104,202002,7E59G71FF10,N,N,32,1,14129,NaN
1,20200208,202003,7E59G71FF10,N,N,32,1,14129,NaN
2,20200307,202004,7E59G71FF10,N,N,32,1,14129,NaN
3,20200411,202005,7E59G71FF10,N,N,32,1,14129,NaN
4,20200509,202006,7E59G71FF10,N,N,32,1,14129,NaN
5,20200607,202007,7E59G71FF10,N,N,32,1,14129,NaN
6,20200711,202008,7E59G71FF10,N,N,32,1,14129,NaN
7,20200808,202009,7E59G71FF10,N,N,32,1,14129,NaN
8,20200912,202010,7E59G71FF10,N,N,32,1,14129,NaN
9,20201010,202011,7E59G71FF10,N,N,32,1,14129,NaN
10,20201107,202012,7E59G71FF10,N,N,32,1,14129,NaN
11,20201205,202101,7E59G71FF10,N,N,31.5,1,14129,NaN
12,20210110,202102,7E59G71FF10,N,N,31.5,1,14129,NaN
13,20210206,202103,7E59G71FF10,N,N,31.5,1,14129,NaN
14,20210306,202104,7E59G71FF10,N,N,31.5,1,14129,NaN
15,20210410,202105,7E59G71FF10,N,N,-31.5,1,14129,NaN
16,20210606,202107,7E59G71FF10,N,N,0,1,14129,NaN

In [20]:
# Elig
df_prev = df_prev_elig.query(f'memnbr == "{memnbr}"').reset_index(drop=True)

n_prev = df_prev.shape[0]
print(f'{n_prev} records for previous submission.')
display(df_prev)

df_current = df_elig.query(f'memnbr == "{memnbr}"').reset_index(drop=True)

n = df_current.shape[0]
print(f'\n{n} records for current submission.')
display(df_current)

2 records for previous submission.

,memnbr,REP_POP_ID,PO_NBR,mcd_cat,SNPTYPE,elig_start,elig_end,delig_ind,hospice_ben,medical_ben,rx_ben,dental_ben,mh_inp_ben,mh_dn_ben,mh_outer_ben,cd_inp_ben,cd_dn_ben,cd_outer_ben
0,7E59G71FF10,14129,NaN,NaN,9,20200101,20200930,P,N,Y,Y,Y,Y,Y,Y,Y,Y,Y
1,7E59G71FF10,14129,NaN,NaN,9,20201001,20210331,P,N,Y,Y,Y,Y,Y,Y,Y,Y,Y

2 records for current submission.

,memnbr,REP_POP_ID,PO_NBR,mcd_cat,SNPTYPE,elig_start,elig_end,delig_ind,hospice_ben,medical_ben,rx_ben,dental_ben,mh_inp_ben,mh_dn_ben,mh_outer_ben,cd_inp_ben,cd_dn_ben,cd_outer_ben
0,7E59G71FF10,14129,NaN,NaN,9,20200101,20200930,P,N,Y,Y,Y,Y,Y,Y,Y,Y,Y
1,7E59G71FF10,14129,NaN,NaN,9,20201001,20210331,P,N,Y,Y,Y,Y,Y,Y,Y,Y,Y

In [21]:
# claims
df_prev = df_prev_clm.query(f'memnbr == "{memnbr}"').reset_index(drop=True)

n_prev = df_prev.shape[0]
print(f'{n_prev} records for previous submission.')
display(df_prev)

df_current = df_claim.query(f'memnbr == "{memnbr}"').reset_index(drop=True)

n = df_current.shape[0]
print(f'\n{n} records for current submission.')
display(df_current)

68 records for previous submission.

,memnbr,claimid,linenbr,fromdt,thrudt,provnbr,provspec,cpt,cptmod1,cptmod2,hcpcs,cpt_ii,cpt_iimod,rev,drg,billtype,factype,pos,tos,dsc,occ_code,icd_format,diag1,diag2,diag3,diag4,diag5,diag6,diag7,diag8,diag9,diag10,diag11,diag12,diag13,diag14,diag15,diag16,diag17,diag18,diag19,diag20,surgproc1,surgproc2,surgproc3,surgproc4,surgproc5,surgproc6,claim_status,covered_days,units,source,src_ind
0,7E59G71FF10,20032601920103100046,1,03/16/2020,03/16/2020,1992796759,99,99203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,77.0,11,NaN,NaN,NaN,10,D0502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
1,7E59G71FF10,20072101820002500010,1,01/11/2020,01/11/2020,1952476665,12,99281,NaN,NaN,NaN,NaN,NaN,0450,NaN,0131,NaN,23,NaN,NaN,NaN,10,L259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
2,7E59G71FF10,20072101920002500005,1,01/11/2020,01/11/2020,1548343510,99,99284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,77.0,23,NaN,NaN,NaN,10,L259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
3,7E59G71FF10,20080301920002500009,1,07/02/2020,07/02/2020,1992796759,99,99213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,77.0,11,NaN,NaN,NaN,10,D0502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
4,7E59G71FF10,21020901920342200032,1,12/29/2020,12/29/2020,1356695092,10,99285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,77.0,23,NaN,NaN,NaN,10,B80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,7E59G71FF10,H964A8D6D,1,10/30/2020,NaN,NaN,NaN,81001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81,NaN,NaN,NaN,10,N390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
64,7E59G71FF10,H964A8D6E,1,10/30/2020,NaN,1811997711,99,80307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81,NaN,NaN,NaN,10,M159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
65,7E59G71FF10,H964A8E60,1,12/31/2020,NaN,1548294267,1,99214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,10,E1169,B80,R109,F1510,K5900,Z993,I10,Z8659,E785,F209,Z7689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
66,7E59G71FF10,H964A8E68,1,12/30/2020,NaN,1548294267,1,99490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,10,I10,E7849,F209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
67,7E59G71FF10,H964A8E68,2,12/30/2020,NaN,1548294267,1,G2058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,10,I10,E7849,F209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,2,P,NaN

68 records for current submission.

,memnbr,claimid,linenbr,fromdt,thrudt,provnbr,provspec,cpt,cptmod1,cptmod2,hcpcs,cpt_ii,cpt_iimod,rev,drg,billtype,factype,pos,tos,dsc,occ_code,icd_format,diag1,diag2,diag3,diag4,diag5,diag6,diag7,diag8,diag9,diag10,diag11,diag12,diag13,diag14,diag15,diag16,diag17,diag18,diag19,diag20,surgproc1,surgproc2,surgproc3,surgproc4,surgproc5,surgproc6,claim_status,covered_days,units,source,src_ind
0,7E59G71FF10,H849A21CC,1,06/24/2020,NaN,1003038860,99,73562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,10,M1712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
1,7E59G71FF10,H849BDB11,1,02/29/2020,NaN,1548294267,1,99490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,10,I10,E7849,F209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
2,7E59G71FF10,H849BDE30,1,01/14/2020,NaN,1548294267,1,99213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,10,T7840XD,I10,E785,G40909,Z6842,F209,F322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
3,7E59G71FF10,H849BDE30,2,01/14/2020,NaN,1548294267,1,1036F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,10,T7840XD,I10,E785,G40909,Z6842,F209,F322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
4,7E59G71FF10,H849BDE30,3,01/14/2020,NaN,1548294267,1,4010F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,NaN,NaN,NaN,10,T7840XD,I10,E785,G40909,Z6842,F209,F322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,7E59G71FF10,21082701820221500072,2,12/29/2020,12/29/2020,1487694857,12,80053,NaN,NaN,NaN,NaN,NaN,0301,NaN,131,NaN,23,NaN,NaN,NaN,10,NaN,I10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
64,7E59G71FF10,21082701820221500072,3,12/29/2020,12/29/2020,1487694857,12,85025,NaN,NaN,NaN,NaN,NaN,0305,NaN,131,NaN,23,NaN,NaN,NaN,10,NaN,NaN,I10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
65,7E59G71FF10,21082701820221500072,4,12/29/2020,12/29/2020,1487694857,12,81003,NaN,NaN,NaN,NaN,NaN,0307,NaN,131,NaN,23,NaN,NaN,NaN,10,NaN,NaN,NaN,I10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
66,7E59G71FF10,21082701820221500072,5,12/29/2020,12/29/2020,1487694857,12,99284,NaN,NaN,NaN,NaN,NaN,0450,NaN,131,NaN,23,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,I10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN
67,7E59G71FF10,21082701820221500072,6,12/29/2020,12/29/2020,1487694857,12,J7030,NaN,NaN,NaN,NaN,NaN,0636,NaN,131,NaN,23,NaN,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,I10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,1,1,P,NaN

In [22]:
# claim mismatch prev -> current
df_prev.merge(df_current[['claimid', 'linenbr']], on=['claimid', 'linenbr'], how='left', indicator=True).query('_merge != "both"')

Empty DataFrame
Columns: [memnbr, claimid, linenbr, fromdt, thrudt, provnbr, provspec, cpt, cptmod1, cptmod2, hcpcs, cpt_ii, cpt_iimod, rev, drg, billtype, factype, pos, tos, dsc, occ_code, icd_format, diag1, diag2, diag3, diag4, diag5, diag6, diag7, diag8, diag9, diag10, diag11, diag12, diag13, diag14, diag15, diag16, diag17, diag18, diag19, diag20, surgproc1, surgproc2, surgproc3, surgproc4, surgproc5, surgproc6, claim_status, covered_days, units, source, src_ind, _merge]
Index: []

In [23]:
# claim mismatch current -> prev
df_current.merge(df_prev[['claimid', 'linenbr']], on=['claimid', 'linenbr'], how='left', indicator=True).query('_merge != "both"')

Empty DataFrame
Columns: [memnbr, claimid, linenbr, fromdt, thrudt, provnbr, provspec, cpt, cptmod1, cptmod2, hcpcs, cpt_ii, cpt_iimod, rev, drg, billtype, factype, pos, tos, dsc, occ_code, icd_format, diag1, diag2, diag3, diag4, diag5, diag6, diag7, diag8, diag9, diag10, diag11, diag12, diag13, diag14, diag15, diag16, diag17, diag18, diag19, diag20, surgproc1, surgproc2, surgproc3, surgproc4, surgproc5, surgproc6, claim_status, covered_days, units, source, src_ind, _merge]
Index: []